### ISSUE TITLE
Set up git-lfs with with Box, Dropbox, or equivalent

### ISSUE THREAD

**Issue by gregerhardt** [tscore-utc/scenarios#17]

**Comment by gregmacfarlane** [comment]
I'm not sure exactly what this means; is it possible to use git-lfs with Box as a storage server? Or do you mean figure out which files go in LFS and which files go in Box?

**Comment by gregerhardt** [comment]
This seems to work.  Need to make sure git lfs is installed before cloning the repository.  See: https://git-lfs.github.com/
