### ISSUE TITLE
SF-TSCORE Scenario run getting stuck

### ISSUE THREAD

**Issue by jawadmhoque** [tscore-utc/scenarios#23]
Model Config: SF-CHAMP network.xml converted to pbf format using LBNL converter PhyssimToOsmConverter.scala.

Log File attached.
[beamLog.txt](https://github.com/tscore-utc/scenarios/files/6505110/beamLog.txt)

**Comment by gregerhardt** [comment]
I think you need to look through the code and figure out what's going on with each of the exceptions.

From: Jawad Mahmud Hoque ***@***.***>
Sent: Tuesday, May 18, 2021 8:44 PM
To: tscore-utc/scenarios ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tscore-utc/scenarios] SF-TSCORE Scenario run getting stuck (#23)

CAUTION: External Sender


Model Config: SF-CHAMP network.xml converted to pbf format using LBNL converter PhyssimToOsmConverter.scala.

Log File attached.
beamLog.txt<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftscore-utc%2Fscenarios%2Ffiles%2F6505110%2FbeamLog.txt&data=04%7C01%7Cgreg.erhardt%40uky.edu%7Cd3acf088815a4cbaf3ac08d91a5f4072%7C2b30530b69b64457b818481cb53d42ae%7C0%7C0%7C637569818670485820%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QKFWTOwWU1XcE41Nvz0B9NprKsbxzJZfhLlfQs%2FtXbE%3D&reserved=0>

-

**Comment by jawadmhoque** [comment]
Fixed. The issue was with the MATSim network created from SF-CHAMP outputs. Fixed it engaging BEAM to create the MATSim network from OSM file. 
Ran the PhyssimToOsmConverter.scala on the MATSim network file created from SF-CHAMP network. (sf-osm-from-matsim.osm.pbf). Kept only this file in the r5 folder in the scenario. BEAM creates the new network from this OSM file and names it according to the specification in the config file (line 67: beam.physsim.inputNetworkFilePath = ${beam.inputDirectory}"/r5/osm_to_matsim_network.xml.gz"). This new file is then created in the r5 folder.
